---
title: "A genome-wide gene expression analysis in APP-transgenic mice during development"
author: "Xulong Wang"
output: 
  ioslides_presentation:
    widescreen: true
    smaller: true
---

```{r, echo=F, warning=F, message=F}
library(ape)
library(amap)
library(ggdendro)
library(MASS)
library(gplots)
library(ggplot2)
library(ggvis)
library(pheatmap)
library(grid)
library(dplyr)
library(contrast)
library(multcomp)
library(png)

rm(list = ls())
setwd("~/Dropbox/GitHub/Ad")
load("./data/brain2014.rdt"); glm.dt <- brain.tpm
# load("./data/retina2014.rdt"); glm.dt <- retina.tpm
source("function.R")
```

## Samples

```{r echo=F, warning=F, fig.height=3.5, fig.width=4}
cutoff <- quantile(c(as.matrix(glm.dt)), 0.25)  # TPM level
glm.dt <- glm.dt[apply(glm.dt, 1, function(x) max(x) > cutoff & sum(x > 0) > round(ncol(glm.dt) / 10)), ]

age <- factor(gsub("^.*(2m|4m|5m|6m).*", "\\1", colnames(glm.dt)), levels = c("2m", "4m", "5m", "6m"))
group <- factor(gsub("^.*(WT|APP).*", "\\1", colnames(glm.dt)), levels = c("WT", "APP"))
uid <- paste(age, group, sep = "_"); table(uid)
batch <- factor(gsub("^.*(2014|mouse).*", "\\1", colnames(glm.dt)), levels = c("2014", "mouse"))
conditions <- c("2m_WT", "2m_APP", "4m_WT", "4m_APP", "5m_WT", "5m_APP", "6m_WT", "6m_APP")
conditions <- conditions[conditions %in% uid]
cat("data:", dim(glm.dt))
par(mar = c(5, 5, 0, 2))
hist(c(as.matrix(brain.tpm)), main = NULL, xlab = "Log2(TPM)", col = "dodgerblue3", border = "white")
```

## Model the data with GLM

$y \sim age + group + batch + age * group$ -> $y \sim age + group + age * group$

```{r echo=F, warning=F}
fit0 <- apply(glm.dt, 1, function (x) summary(lm(x ~ age + group + batch + age*group)))
fit0.batch <- sapply(fit0, function (x) x$coefficients["batchmouse", "Estimate"])
glm.dt_bc <- glm.dt - as.matrix(fit0.batch) %*% (as.numeric(batch) - 1)
glm.fit <- apply(glm.dt_bc, 1, function (x) lm(x ~ age + group + age*group))
cat("App \n"); summary(glm.fit[["App"]])$coefficient

cat("Choose the genes with R2 > 0.3 and Qvalue < 0.05 \n")

fit.r2 <- sapply(glm.fit, function (x) summary(x)$r.squared)
fit.qval <- sapply(glm.fit, function (x) summary(x)$fstatistic) %>% 
  apply(2, function (x) pf(x[1], x[2], x[3], lower.tail = F)) %>% p.adjust(method = "fdr")

glm.fit <- glm.fit[fit.qval < 0.05 & fit.r2 > 0.3]
cat("New:", length(glm.fit))
```

## Age, App, and age_App_inter genes with ANOVA

Normal aging genes, 2-month app genes, age-dependent app genes (4, 5, 6 months)

```{r echo=F, warning=F}
fit.anova <- lapply(glm.fit, anova)
fit.anova[["App"]]
```

## Age, App, and Age_App_inter genes with ANOVA

```{r echo=F, warning=F, fig.width=6, fig.height=5}
genes.aov <- lapply(c("age", "group", "age:group"), function(x1) {
  y1 = sapply(fit.anova, function(x2) x2[x1, "Pr(>F)"]); y1[y1 < 0.05]
}); names(genes.aov) <- c("age", "app", "age:app")
sapply(genes.aov, function(x) length(x))
par(mar = c(5, 5, 0, 2))
venn(list(age = names(genes.aov[[1]]), APP = names(genes.aov[[2]]), age_int_app = names(genes.aov[[3]])))
```

## Age-specific APP effect

```{r echo=F, warning=F}
age_spe <- lapply(c("2m", "4m", "5m", "6m"), function(x1) {
  y1 = sapply(glm.fit, function(x2) {
    y2 = contrast(x2, list(age = x1, group = "APP"), list(age = x1, group = "WT"))
    c(y2$Contrast, y2$Pvalue)
  }); rownames(y1) = c("contrast", "pval"); t(y1)
}); names(age_spe) <- c("2m", "4m", "5m", "6m")

cat("Stat3 \n")
sapply(c("2m", "4m", "5m", "6m"), function(x1) {
  contrast(glm.fit[["Stat3"]], list(age = x1, group = "APP"), list (age = x1, group = "WT"))  
})[c("Contrast", "Pvalue"), ]

age_spe_up <- sapply(age_spe, function(x) x[x[, 1] > 0.1 & x[, 2] < 0.05, ])
age_spe_dn <- sapply(age_spe, function(x) x[x[, 1] < -0.1 & x[, 2] < 0.05, ])
cat("Age-specific APP genes: up (contrast > 0.1, pvalue < 0.05) \n"); sapply(age_spe_up, function(x) nrow(x)) 
cat("Age-specific APP genes: down (contrast < -0.1, pvalue < 0.05) \n"); sapply(age_spe_dn, function(x) nrow(x))
```

## WT-specific age effect (normal aging genes)

```{r echo=F, warning=F}
combn <- combn(c("2m", "4m", "5m", "6m"), 2)
geno_spec_wt <- lapply(1:ncol(combn), function(x1) {
  y1 = sapply(glm.fit, function(x2) {
    y2 = contrast(x2, list(age = combn[2, x1], group = "WT"), list(age = combn[1, x1], group = "WT")) 
    c(y2$Contrast, y2$Pvalue)
  }); rownames(y1) = c("contrast", "pval"); t(y1)
}); names(geno_spec_wt) <- apply(combn, 2, function(x) paste0(x[2], "_vs_", x[1])) 

cat("Stat3 \n")
sapply(1:ncol(combn), function(x1) {
  contrast(glm.fit[["Stat3"]], list(age = combn[2, x1], group = "WT"), list(age = combn[1, x1], group = "WT")) 
})[c("Contrast", "Pvalue"), ]

geno_spec_wt_up <- sapply(geno_spec_wt, function(x) x[x[, 1] > 0.1 & x[, 2] < 0.05, ])
geno_spec_wt_dn <- sapply(geno_spec_wt, function(x) x[x[, 1] < -0.1 & x[, 2] < 0.05, ])
cat("WT-specific aging genes: up (contrast > 0.1, pvalue < 0.05) \n"); sapply(geno_spec_wt_up, function(x) nrow(x)) 
cat("WT-specific aging genes: down (contrast < -0.1, pvalue < 0.05) \n"); sapply(geno_spec_wt_dn, function(x) nrow(x))
```

## APP-specific age effect (app-specific aging genes)
```{r echo=F, warning=F}
C <- matrix(c(0,0,0,0,0,0,-1,1), 1) 
cat("6m APP vs 5m APP Stat3: \n"); summary(glht(glm.fit[["Stat3"]], linfct = C))
```
